.env
.gitignore

feature/rank -> prod
- 이전에 서브모듈 작업을 예상하고 .env를 ignore에 넣었었는데 merge할 때도 적용이 되지 않아서 우선 제외하고 pr합니다.

CHORE: ignore, 환경변수 작업

---

src/api/customAxios.js

feature/rank -> prod
base url을 수정했습니다.

FEAT: base url 수정

---

src/tap/fav/FavTap.js
src/tap/rank/RankTap.js
src/tap/search/SearchTap.js

feature/rank -> prod
- 기존 목업 데이터 형식을 지우고 api 요청대로 수정했습니다.

FEAT: api 데이터 형식으로 목업 데이터 교체

---

src/hooks/useGroup.js
src/tap/group/components/ui-components/GroupCreate.js

feature/group -> prod
axios 경로 수정하였습니다 ..

CHORE: axios 경로 수정했습니다

---

src/tap/group/components/ui-components/GroupCreate.js

FEAT: 콘솔로그 추가

---

src/mooks/handler.js
src/tap/group/components/atom-components/Seleter.js
src/tap/group/components/ui-components/GroupCreate.js
src/tap/group/components/ui-components/GroupDetail.js

FEAT: groupTitle => title

---

src/hooks/useGroup.js

CHORE: axios 테스트

---

src/hooks/useFriends.js
src/hooks/useGroup.js

FEAT: 그룹생성 로직 수정 제발 되어라

---

src/tap/marker/MarkerTap.js
src/tap/marker/ui_components/GroupSelect.js
src/tap/marker/ui_components/MarkerModal.js
src/tap/marker/ui_components/MarkerModal.module.css

real plz..

---

src/tap/marker/ui_components/MarkerModal.js

+application/json

---

src/hooks/useGroup.js
src/tap/group/GroupTap.js
src/tap/group/components/ui-components/GroupDetail.js

FIX: 함수 무한호출 로직 수정 , getGroup로직변경

---

src/App.js
src/hooks/useGroup.js
src/tap/group/components/atom-components/Seleter.js

FIX: 그룹 이동 안되는 버그 수정

---

src/hooks/useGroup.js
src/tap/group/components/atom-components/Seleter.js
src/tap/group/components/ui-components/GroupDetail.js
src/tap/group/components/ui-components/GroupFriends.js

FIX: 그룹마커 재렌더링 안되는 버그 수정

---

src/common/frame/MainMap.js

FEAT: 그룹마커보여주기 기능 구현 #1

---

src/common/frame/MainMap.js
src/common/frame/Sidebar.js
src/tap/group/GroupTap.js

FEAT: 그룹마커 보여주기 기능 #2 (배열로)

---

src/tap/marker/MarkerTap.js
src/tap/marker/ui_components/GroupSelect.js

[FIX] 무한로딩

---

src/tap/marker/MarkerTap.js
src/tap/marker/ui_components/GroupSelect.js

refactoring

---

src/tap/marker/ui_components/GroupSelect.js

refactoring marker

---

src/common/frame/MainMap.js

FEAT: 그룹 초기화 로직 생성

---

src/tap/marker/MarkerTap.js

FEAT: Seleter 추가

---

src/tap/marker/MarkerTap.js
src/tap/route/RouteTap.js
src/tap/route/RouteTap.module.css
src/tap/route/ui_components/MarkerSelectModal.js

MarkerTest

---

src/tap/group/components/atom-components/Seleter.js

FIX: import 에러 수정

---

src/hooks/useGroup.js
src/tap/group/GroupTap.js
src/tap/group/components/ui-components/GroupFriends.js

FEAT: 삭제 리렌더링 구현
